### ISSUE TITLE
Issue with alerting?

### ISSUE THREAD

**Issue by killmasta93** [uvoteam/pve-zsync-monitoring#1]
Hi,
found this repo to install on my zabbix server to monitor proxmox pve-zync, if i read correctly
i would put the zsync-zbx.py inside the folder of the client inside /etc/zabbix
then inside of /etc/zabbix/zabbix_agentd.conf.d i would put pve-zsync.conf then restart the zabbix client service, on the zabbix server add the xml template and add the template on the proxmox server, i tested it out by disconnecting one of the host so i would get an alert of the PVE-zync which it failed but did not alert on zabbix server any ideas?

Thank you

**Comment by firaxis** [comment]
Hi,
Well, first of all, I don't know if it's a not working script or problems with notifications..
Try to look into /tmp/zsync-zbx.log, /tmp/zsync.status.dat or try to execute the script manually, maybe it will produce some output.

**Comment by killmasta93** [comment]
Thanks for the reply, i checked inside /tmp/ of the server and client but no logs seem to exist

**Comment by firaxis** [comment]
Then, looks like the script isn't bring executed.
Try to make zabbix execute the script.

**Comment by firaxis** [comment]
Then, looks like the script isn't bring executed.
Try to make zabbix execute the script.

**Comment by killmasta93** [comment]
Thanks for the reply, well what i did see is that the zsync-zbx.py script did not have the permissions but this is what i did

`root@prometheus3:/etc/zabbix# chmod +x  zsync-zbx.py   

root@prometheus3:/etc/zabbix# ./zsync-zbx.py 

Traceback (most recent call last):
  File "./zsync-zbx.py", line 100, in <module>
    jobs = zsync(statefile = "sync_state")
  File "./zsync-zbx.py", line 20, in __init__
    with open(self.statefile, "r") as config:
FileNotFoundError: [Errno 2] No such file or directory: 'sync_state'
`

**Comment by firaxis** [comment]
Looks like I've missed to specify a correct pve-zsync state file path.
Please, check out a new version.

**Comment by killmasta93** [comment]
Thank you now i run this it seems to find the pve syncs but zabbix shows no data

root@prometheus3:/etc/zabbix# service zabbix-agent restart
root@prometheus3:/etc/zabbix# ./zsync-zbx.py  --discover
{
    "data":[
        {
            "{#REPLICA}":"test2"
        }
    ]
}
root@prometheus3:/etc/zabbix# ./zsync-zbx.py  --send
1

**Comment by killmasta93** [comment]
on the zsync.status.dat i get this
  GNU nano 2.7.4                                                                                                 File: zsync.status.dat                                                                                                           

prometheus3.casa.local zsync.lsync[test2] 14109
prometheus3.casa.local zsync.state[test2] error

and on 
zsync-zbx.log
i get this 
Response from "192.168.3.160:10051": "processed: 0; failed: 2; total: 2; seconds spent: 0.000022"
sent: 2; skipped: 0; total: 2

but no alert on zabbix

**Comment by firaxis** [comment]
Please, look into zabbix-server logs, you should see why the metrics are failed, e.g. hostname mismatch.

**Comment by killmasta93** [comment]
thanks for the reply, i checked the logs does not show any event related to pve. I re ran the command

./zsync-zbx.py --discover --send 

to see if in the logs of the server appears and it does not,
