### ISSUE TITLE
issue  invalid with discovery rule

### ISSUE THREAD

**Issue by killmasta93** [uvoteam/pve-zsync-monitoring#2]
Hi,
currently checking the discovery log and found this which the data is not coming in

`Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sh: 1: /etc/zabbix/zsync-zbx.py: not found`
 with python 
```

Reading state information... Done
python3 is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 88 not upgraded.
```

zabbix 4.4
and proxmox 5.4

Thank you

**Comment by firaxis** [comment]
Hi,
Please, ensure that /etc/zabbix/zsync-zbx.py exists.

**Comment by killmasta93** [comment]
Thanks for the reply, i had it in the folder scripts, 

Out of curiosity the alerts only if pve-zsync fails or does it also check if its longer then 24 hours the backup? 

Currently ran a test for it to have an error
```

SOURCE                   NAME                     STATE     LAST SYNC           TYPE  CON  
124                      baktest                  error     2020-02-01_17:00:01 qemu  ssh 
```

checked if it sends to Zabbix 

```
root@prometheus3:/etc/zabbix# ./zsync-zbx.py --discover
{
    "data":[
        {
            "{#REPLICA}":"baktest"
        }
    ]
}

```

then checked on zabbix the time shows 17:07 and the error on server is on 17:00 so not sure if the time checks are 24 hours 

![image](https://user-images.githubusercontent.com/13953629/73599810-e6fa1400-4515-11ea-95a7-1f936a8dc882.png)

**Comment by firaxis** [comment]
Looks like the script doesn't send status.
Unfortunately, I don't have any proxmox nearby to check or fix it, sorry.
